---

- name: caddy | check if caddy is installed
  stat:
    path: "/usr/local/bin/caddyserver"
  register: __caddy_is_installed
  become: true
  tags: caddy

- name: caddy | copy binary file
  copy:
    src: "caddyserver"
    dest: "/usr/local/bin/caddy"
    owner: root
    group: root
    mode: 0755
  when: not __caddy_is_installed.stat.exists
  become: true
  tags: caddy

- name: caddy | create default directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0755
  with_items:
    - /etc/caddy
    - /var/lib/caddy
    - /var/lib/caddy/.storage
    - "{{ caddy_log_folder }}"
    - "{{ caddy_web_path }}"
  become: true
  tags: caddy

- name: caddy | configure index.html
  template:
    src: caddy.index.html.j2
    dest: "{{ caddy_web_path }}/index.html"
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0644
  become: true
  tags: caddy

- name: caddy | configure logrotate
  template:
    src: caddy.logrotate.j2
    dest: "/etc/logrotate.d/caddy"
    owner: root
    group: root
    mode: 0644
  become: true
  tags: caddy

- name: caddy | create config
  template:
    src: caddy.conf.j2
    dest: /etc/caddy/caddy.conf
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    mode: 0644
  notify: restart caddy
  become: true
  tags: caddy

- block:
  - name: caddy | generate ufw application file
    template:
      src: caddy.ufw.app.j2
      dest: "/etc/ufw/applications.d/caddy"
      owner: root
      group: root
      mode: 0644
    register: __ufw_caddy_app
    become: true
    tags: caddy

  - name: caddy | reload ufw
    command: ufw reload
    when: __ufw_caddy_app.changed
    become: true
    tags: caddy

  - name: caddy | allow port on ufw
    ufw:
      rule: allow
      name: Caddy
    become: true
    tags: caddy
  when: "'ufw' in ansible_facts.packages"

- name: caddy | create systemd unit
  template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root
    mode: 0644
  notify: restart caddy
  become: true
  tags: caddy

- name: caddy | start and enable service
  systemd:
    daemon_reload: true
    name: caddy
    state: started
    enabled: true
  become: true
  tags: caddy

