---
- name: gather operating system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - caddy
    - pac
    - socks
    - squid
    - squidguard

- name: "check if ufw is installed"
  package_facts:
    manager: "ufw"
  tags:
    - caddy
    - socks
    - squid

- name: install caddyserver
  include_tasks: caddy.yml
  when: caddy_enabled

- name: install pac
  include_tasks: pac.yml
  when: pac_enabled and caddy_enabled

- name: install socks
  include_tasks: socks.yml
  when: socks_enabled

- name: install squid
  include_tasks: squid.yml
  when: squid_enabled

- name: install squidguard
  include_tasks: squidguard.yml
  when: squid_enabled and squidguard_enabled